/*
 * Selling Partner API for Listings Items
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2021-08-01.md).
 *
 * OpenAPI spec version: 2021-08-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.listingsItems_2021_08_01;

import com.amazon.xingapi.SellingPartnerAPIAA.AWSAuthenticationCredentials;
import com.amazon.xingapi.SellingPartnerAPIAA.AWSAuthenticationCredentialsProvider;
import com.amazon.xingapi.SellingPartnerAPIAA.LWAAuthorizationCredentials;
import com.amazon.xingapi.client.ApiException;
import com.amazon.xingapi.api.listingsItems_2021_08_01.ListingsApi;
import com.amazon.xingapi.model.listingsItems_2021_08_01.*;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ListingsApi
 */
@Ignore
public class ListingsApiTest {

    private final ListingsApi api = new ListingsApi();

    
    /**
     * 
     *
     * Delete a listings item for a selling partner.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteListingsItemTest() throws ApiException {
        String sellerId = null;
        String sku = null;
        List<String> marketplaceIds = null;
        String issueLocale = null;
        ListingsItemSubmissionResponse response = api.deleteListingsItem(sellerId, sku, marketplaceIds, issueLocale);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns details about a listings item for a selling partner.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getListingsItemTest() throws ApiException {
        ListingsApi listingsApi = getListingsApi();
        String sellerId = "";
        String sku = "";
        List<String> marketplaceIds = new ArrayList<>();
        String issueLocale = "en_US";
        List<String> includedData = new ArrayList<>();
//        marketplaceIds.add("ATVPDKIKX0DER");
        marketplaceIds.add("A2EUQ1WTGCTBG2");
        includedData.add("summaries");
        includedData.add("attributes");
        includedData.add("issues");
        includedData.add("offers");
        includedData.add("fulfillmentAvailability");
//        includedData.add("procurement");
        Item response = listingsApi.getListingsItem(sellerId, sku, marketplaceIds, issueLocale, includedData);

        Object itemAttributes = response.getAttributes();
//        System.out.println(itemAttributes);
//
        System.out.println(response);

        // TODO: test validations
    }

    public static ListingsApi getListingsApi() {
        AWSAuthenticationCredentials awsAuthenticationCredentials = AWSAuthenticationCredentials.builder()
                .accessKeyId("")
                .secretKey("")
                .region("")
                .build();
        AWSAuthenticationCredentialsProvider awsAuthenticationCredentialsProvider = AWSAuthenticationCredentialsProvider.builder()
                .roleArn("")
                .roleSessionName("")
                .build();
        LWAAuthorizationCredentials lwaAuthorizationCredentials = LWAAuthorizationCredentials.builder()
                .clientId("")
                .clientSecret("")
                .refreshToken("")
                .endpoint("https://api.amazon.com/auth/o2/token")
                .build();


        ListingsApi listingsApi  = new ListingsApi.Builder()
                .awsAuthenticationCredentials(awsAuthenticationCredentials)
                .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
                .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
                .endpoint("https://sellingpartnerapi-na.amazon.com")
                .build();

        return listingsApi;

    }
    /**
     * 
     *
     * Partially update (patch) a listings item for a selling partner. Only top-level listings item attributes can be patched. Patching nested attributes is not supported.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchListingsItemTest() throws ApiException {
        String sellerId = null;
        String sku = null;
        List<String> marketplaceIds = null;
        ListingsItemPatchRequest body = null;
        String issueLocale = null;
        ListingsItemSubmissionResponse response = api.patchListingsItem(sellerId, sku, marketplaceIds, body, issueLocale);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Creates a new or fully-updates an existing listings item for a selling partner.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putListingsItemTest() throws ApiException {
        String sellerId = null;
        String sku = null;
        List<String> marketplaceIds = null;
        ListingsItemPutRequest body = null;
        String issueLocale = null;
        ListingsItemSubmissionResponse response = api.putListingsItem(sellerId, sku, marketplaceIds, body, issueLocale);

        // TODO: test validations
    }
    
}
