/*
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.productPricingV0;

import com.amazon.xingapi.client.ApiException;
import com.amazon.xingapi.api.productPricingV0.ProductPricingApi;
import com.amazon.xingapi.model.productPricingV0.GetOffersResponse;
import com.amazon.xingapi.model.productPricingV0.GetPricingResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductPricingApi
 */
@Ignore
public class ProductPricingApiTest {

    private final ProductPricingApi api = new ProductPricingApi();

    
    /**
     * 
     *
     * Returns competitive pricing information for a seller&#39;s offer listings based on seller SKU or ASIN.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 10 | 20 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompetitivePricingTest() throws ApiException {
        String marketplaceId = null;
        String itemType = null;
        List<String> asins = null;
        List<String> skus = null;
        String customerType = null;
        GetPricingResponse response = api.getCompetitivePricing(marketplaceId, itemType, asins, skus, customerType);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns the lowest priced offers for a single item based on ASIN.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 5 | 10 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getItemOffersTest() throws ApiException {
        String marketplaceId = null;
        String itemCondition = null;
        String asin = null;
        String customerType = null;
        GetOffersResponse response = api.getItemOffers(marketplaceId, itemCondition, asin, customerType);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns the lowest priced offers for a single SKU listing.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 5 | 10 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getListingOffersTest() throws ApiException {
        String marketplaceId = null;
        String itemCondition = null;
        String sellerSKU = null;
        String customerType = null;
        GetOffersResponse response = api.getListingOffers(marketplaceId, itemCondition, sellerSKU, customerType);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns pricing information for a seller&#39;s offer listings based on seller SKU or ASIN.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 10 | 20 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPricingTest() throws ApiException {
        String marketplaceId = null;
        String itemType = null;
        List<String> asins = null;
        List<String> skus = null;
        String itemCondition = null;
        String offerType = null;
        GetPricingResponse response = api.getPricing(marketplaceId, itemType, asins, skus, itemCondition, offerType);

        // TODO: test validations
    }
    
}
