/*
 * Selling Partner API for Direct Fulfillment Payments
 * The Selling Partner API for Direct Fulfillment Payments provides programmatic access to a direct fulfillment vendor's invoice data.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.vendorDirectFulfillmentPaymentsV1;

import com.amazon.xingapi.client.ApiException;
import com.amazon.xingapi.api.vendorDirectFulfillmentPaymentsV1.VendorInvoiceApi;
import com.amazon.xingapi.model.vendorDirectFulfillmentPaymentsV1.SubmitInvoiceRequest;
import com.amazon.xingapi.model.vendorDirectFulfillmentPaymentsV1.SubmitInvoiceResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VendorInvoiceApi
 */
@Ignore
public class VendorInvoiceApiTest {

    private final VendorInvoiceApi api = new VendorInvoiceApi();

    
    /**
     * 
     *
     * Submits one or more invoices for a vendor&#39;s direct fulfillment orders.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 10 | 10 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void submitInvoiceTest() throws ApiException {
        SubmitInvoiceRequest body = null;
        SubmitInvoiceResponse response = api.submitInvoice(body);

        // TODO: test validations
    }
    
}
