/*
 * Selling Partner API for Retail Procurement Payments
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.vendorInvoices;

import com.amazon.xingapi.client.ApiException;
import com.amazon.xingapi.api.vendorInvoices.VendorPaymentsApi;
import com.amazon.xingapi.model.vendorInvoices.SubmitInvoicesRequest;
import com.amazon.xingapi.model.vendorInvoices.SubmitInvoicesResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VendorPaymentsApi
 */
@Ignore
public class VendorPaymentsApiTest {

    private final VendorPaymentsApi api = new VendorPaymentsApi();

    
    /**
     * 
     *
     * Submit new invoices to Amazon.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 10 | 10 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void submitInvoicesTest() throws ApiException {
        SubmitInvoicesRequest body = null;
        SubmitInvoicesResponse response = api.submitInvoices(body);

        // TODO: test validations
    }
    
}
