/*
 * Selling Partner API for Direct Fulfillment Shipping
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.vendorDirectFulfillmentShippingV1;

import com.amazon.xingapi.client.ApiException;
import com.amazon.xingapi.api.vendorDirectFulfillmentShippingV1.CustomerInvoicesApi;
import com.amazon.xingapi.model.vendorDirectFulfillmentShippingV1.GetCustomerInvoiceResponse;
import com.amazon.xingapi.model.vendorDirectFulfillmentShippingV1.GetCustomerInvoicesResponse;
import org.threeten.bp.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomerInvoicesApi
 */
@Ignore
public class CustomerInvoicesApiTest {

    private final CustomerInvoicesApi api = new CustomerInvoicesApi();

    
    /**
     * 
     *
     * Returns a customer invoice based on the purchaseOrderNumber that you specify.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 10 | 10 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCustomerInvoiceTest() throws ApiException {
        String purchaseOrderNumber = null;
        GetCustomerInvoiceResponse response = api.getCustomerInvoice(purchaseOrderNumber);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns a list of customer invoices created during a time frame that you specify. You define the  time frame using the createdAfter and createdBefore parameters. You must use both of these parameters. The date range to search must be no more than 7 days.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 10 | 10 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCustomerInvoicesTest() throws ApiException {
        OffsetDateTime createdAfter = null;
        OffsetDateTime createdBefore = null;
        String shipFromPartyId = null;
        Integer limit = null;
        String sortOrder = null;
        String nextToken = null;
        GetCustomerInvoicesResponse response = api.getCustomerInvoices(createdAfter, createdBefore, shipFromPartyId, limit, sortOrder, nextToken);

        // TODO: test validations
    }
    
}
