/*
 * Selling Partner API for Direct Fulfillment Shipping
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.vendorDirectFulfillmentShippingV1;

import com.amazon.xingapi.client.ApiException;
import com.amazon.xingapi.api.vendorDirectFulfillmentShippingV1.VendorShippingApi;
import com.amazon.xingapi.model.vendorDirectFulfillmentShippingV1.GetPackingSlipListResponse;
import com.amazon.xingapi.model.vendorDirectFulfillmentShippingV1.GetPackingSlipResponse;
import org.threeten.bp.OffsetDateTime;
import com.amazon.xingapi.model.vendorDirectFulfillmentShippingV1.SubmitShipmentConfirmationsRequest;
import com.amazon.xingapi.model.vendorDirectFulfillmentShippingV1.SubmitShipmentConfirmationsResponse;
import com.amazon.xingapi.model.vendorDirectFulfillmentShippingV1.SubmitShipmentStatusUpdatesRequest;
import com.amazon.xingapi.model.vendorDirectFulfillmentShippingV1.SubmitShipmentStatusUpdatesResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VendorShippingApi
 */
@Ignore
public class VendorShippingApiTest {

    private final VendorShippingApi api = new VendorShippingApi();

    
    /**
     * 
     *
     * Returns a packing slip based on the purchaseOrderNumber that you specify.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 10 | 10 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPackingSlipTest() throws ApiException {
        String purchaseOrderNumber = null;
        GetPackingSlipResponse response = api.getPackingSlip(purchaseOrderNumber);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns a list of packing slips for the purchase orders that match the criteria specified. Date range to search must not be more than 7 days.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 10 | 10 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPackingSlipsTest() throws ApiException {
        OffsetDateTime createdAfter = null;
        OffsetDateTime createdBefore = null;
        String shipFromPartyId = null;
        Integer limit = null;
        String sortOrder = null;
        String nextToken = null;
        GetPackingSlipListResponse response = api.getPackingSlips(createdAfter, createdBefore, shipFromPartyId, limit, sortOrder, nextToken);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Submits one or more shipment confirmations for vendor orders.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 10 | 10 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void submitShipmentConfirmationsTest() throws ApiException {
        SubmitShipmentConfirmationsRequest body = null;
        SubmitShipmentConfirmationsResponse response = api.submitShipmentConfirmations(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * This API call is only to be used by Vendor-Own-Carrier (VOC) vendors. Calling this API will submit a shipment status update for the package that a vendor has shipped. It will provide the Amazon customer visibility on their order, when the package is outside of Amazon Network visibility.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 10 | 10 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void submitShipmentStatusUpdatesTest() throws ApiException {
        SubmitShipmentStatusUpdatesRequest body = null;
        SubmitShipmentStatusUpdatesResponse response = api.submitShipmentStatusUpdates(body);

        // TODO: test validations
    }
    
}
